function saveMat( IR_cond, wav_number, seed, it, nb, ns, fsResample, fftSize, shiftSize, ...
                  calc_sdr_ratio, isWhitening, isCalcCost, isOutputWav, isPrintVerbose, ...
                  date, exp_id, method, purpose, memo, ...
                  SDR, SIR, SAR, SDRimp, SIRimp, cost, ...
                  attrs_sdris, attrs_siris, attrs_sar)
%% file name
date_fname    = string(datetime('now','TimeZone','Asia/Tokyo','Format','yyMMdd_HHmmss'));
seed_fname    = strcat("seed", num2str(seed));
fftSize_fname = strcat("fftSize",num2str(fftSize));
shift_fname   = strcat("shift",num2str(shiftSize));
nb_fname      = strcat("nb",num2str(nb));
it_fname      = strcat("it",num2str(it));

fname_arr = [ date_fname, IR_cond, wav_number, fftSize_fname, shift_fname, nb_fname, it_fname, seed_fname ];
filename = join(fname_arr,'_');

%% directory name
nob_dir = strcat("nob_", num2str(nb));
% dirname = strcat(exp_id, music_fname);
% dirname = strcat(dirname, nob_dir);
dirname = strcat("../bss_output/MNMF_results/info/", exp_id, "/", IR_cond, "/", nob_dir, "/", wav_number);
if ~(exist(dirname,'dir')==7)
    mkdir(dirname)
end
dirname = strcat(dirname, "/");

%% save
filepath = strcat(dirname, filename);
save_mat(filepath, ... 
         IR_cond, wav_number, seed, it, nb, ns, fsResample, fftSize, shiftSize, ...
         calc_sdr_ratio, isWhitening, isCalcCost, isOutputWav, isPrintVerbose, ...
         date, exp_id, method, purpose, memo, ...
         SDR, SIR, SAR, SDRimp, SIRimp, cost, ...
         attrs_sdris, attrs_siris, attrs_sar)

fprintf("%s Saved\n", strcat(filepath, '.mat'));
end

function save_mat(filepath, ... 
                  IR_cond, wav_number, seed, it, nb, ns, fsResample, fftSize, shiftSize, ...
                  calc_sdr_ratio, isWhitening, isCalcCost, isOutputWav, isPrintVerbose, ...
                  date, exp_id, method, purpose, memo, ...
                  SDR, SIR, SAR, SDRimp, SIRimp, cost, ...
                  attrs_sdris, attrs_siris, attrs_sar)
n_iter = it;
sampling_freq = fsResample;
fft_size = fftSize;
shift_size = shiftSize;
n_bases = nb;
elapsed_time = datetime('now','TimeZone','Asia/Tokyo') - date;
date = string(date);
elapsed_time = string(elapsed_time);

save(strcat(filepath, '.mat'), ...
        'SDR','SDRimp','SIR','SIRimp','SAR','cost',...
        'calc_sdr_ratio', 'attrs_sdris', 'attrs_siris', 'attrs_sar', ...
        'IR_cond', 'wav_number', 'seed', 'n_iter', 'n_bases',  'ns', ...
        'sampling_freq', 'fft_size', 'shift_size', ...
        'isWhitening', 'isCalcCost', 'isOutputWav', 'isPrintVerbose', ...
        'date', 'elapsed_time', 'exp_id', 'method', 'purpose', 'memo');
end
